#pragma once

enum class ShaderPipelineType {
    EdgeQuad,
    Line,
    LineOverlayFaceNormals,
    LineOverlayVertexNormals,
    Point,
    Grid,
    Background,
    BackgroundVelocity,
    TransmissionComposite,
    MotionBlurResolve,
    SilhouetteEdgeDepthObject,
    SilhouetteEdgeDepth,
    SilhouetteEdgeColor,
    SelectionElementFace,
    SelectionElementEdge,
    SelectionElementVertex,
    SelectionElementFaceBitsetBox,
    SelectionElementEdgeBitsetBox,
    SelectionElementVertexBitsetBox,
    SelectionElementFaceXRay,
    SelectionElementEdgeXRay,
    SelectionElementVertexXRay,
    SelectionElementFaceXRayBitsetBox,
    SelectionElementEdgeXRayBitsetBox,
    SelectionElementVertexXRayBitsetBox,
    SelectionElementEdgeXRayVertsBitsetBox, // Bitset-box variant of the XRay edge point fallback
    SelectionElementFaceXRayVertsBitsetBox, // Bitset-box variant of the XRay face point fallback
    SelectionFragment,
    SelectionFragmentBoneSphere,
    BoneFill,
    BoneWire,
    BoneSphereFill,
    BoneSphereWire,
    ObjectExtrasLine,
    BoundsBox,
    SelectionObjectExtrasLines,
};
