#pragma once

#include "metal/Shader.h"

#include "state/Entity.h"

#include <array>

// Every mesh build pass, grouped by driver in dispatch order.
enum class MeshPass : uint8_t {
    ConnectivityFaces,
    ConnectivityInit,
    ConnectivityInsert,
    ConnectivityMatchEdges,
    ConnectivityResolve,
    ConnectivityLink,
    ConnectivityWordBlockSum,
    ConnectivityWordBlockPrefix,
    ConnectivityRanks,
    ConnectivityCounts,
    ConnectivityRetiredEdges,
    ConnectivityEdgeTables,
    VertexFanInit,
    VertexFanKeys,
    VertexFanTileScan,
    VertexFanTilePrefix,
    VertexFanHistogram,
    VertexFanPrefix,
    VertexFanScatter,
    VertexFanEmit,
    WeldTableInit,
    WeldInsert,
    WeldMarkReps,
    WeldBlockSum,
    WeldBlockPrefix,
    WeldScan,
    WeldEmit,
    WeldRemapCorners,
    WeldCompact,
    WeldWriteBack,
    VertexNormalDerive,
    ElementWorkSeed,
    CornerClassificationCount,
    CornerClassificationPlan,
    CornerClassificationWrite,
    CornerClassificationBlocks,
    MeshClosureCount,
    MeshClosureExpand,
    MeshClosureEdgeVertices,
    MeshClosureTriangles,
    MarkSelectionNeighbors,
    UpdateSelectionBlocks,
    ReduceSelectionRoots,
    GatherSelectedElements,
    ConnectivityEditWork,
    SpatialFaceQueryCount,
    SpatialFaceQueryGather,
    SpatialFaceQueryExpand,
    TopologyIdentityInit,
    TopologyIdentityRetain,
    TopologyIdentityReplaced,
    TopologyIdentityNew,
    TopologyIdentityAssign,
    ElementWorkHistogram,
    ElementWorkPrefix,
    ElementWorkScatter,
    ElementWorkFinish,
    TopologyCollapseKeys,
    TopologyCollapseHistogram,
    TopologyCollapsePrefix,
    TopologyCollapseScatter,
    TopologyCollapseReduce,
    TopologyCollapseCarry,
    TopologyCollapseCenters,
    TopologyZero,
    TopologyMarkHalfedges,
    TopologyMarkFaces,
    TopologyLink,
    TopologyJump,
    TopologyConverge,
    TopologyDissolveRegions,
    TopologyDissolveWalk,
    TopologyDissolveRevert,
    TopologyJoinBest,
    TopologyJoinMatch,
    TopologyZeroVertices,
    TopologyMergeTable,
    TopologyMergeInsert,
    TopologyMergeQuery,
    TopologyLineKeys,
    TopologyDissolveLimitVertices,
    TopologyListFill,
    TopologyCountVertices,
    TopologyCountHalfedges,
    TopologyCountFaces,
    TopologyScanBlockSum,
    TopologyScanBlockPrefix,
    TopologyScanOffsets,
    TopologyScatterVertices,
    TopologyScatterHalfedges,
    TopologyScatterFaces,
    TopologyFaceTables,
    TopologyGatherVertices,
    InsetPreviewPositions,
    MeshletBoundsRefit,
    TopologyGatherCorners,
    TopologyCustomNormals,
    TopologyEdgeAttributes,
    LodNodeRefit,
    MeshletOwners,
    MeshletBuildMaterials,
    MeshletBuildInit,
    MeshletBuildBounds,
    MeshletBuildKeys,
    MeshletBuildHistogram,
    MeshletBuildHistogramPrefix,
    MeshletBuildScatter,
    MeshletBuildSegments,
    MeshletBuildTiles,
    MeshletBuildClusters,
    MeshletBuildOffsets,
    MeshletBuildEmit,
    MeshletBuildPrimitives,
    CloneRebaseIndices,
    CloneCopyReferencePairs,
    Count,
};

struct MeshPipelines {
    explicit MeshPipelines(mtl::LibraryCache &);
    const mtl::ComputePipeline &operator[](MeshPass pass) const { return Pipelines[size_t(pass)]; }

    std::array<mtl::ComputePipeline, size_t(MeshPass::Count)> Pipelines;
};

// Returns the mesh build pipelines, compiling them on first use.
MeshPipelines &GetMeshPipelines(state::Scene &);
