#pragma once

#include "metal/Shader.h"

#include "state/Entity.h"

#include <array>
#include <mutex>
#include <thread>

// Every mesh build pass, grouped by driver in dispatch order.
enum class MeshPass : uint8_t {
    ConnectivityFaces,
    ConnectivityInit,
    ConnectivityInsert,
    ConnectivityMatchEdges,
    ConnectivityClassifyEdges,
    ConnectivityResolve,
    ConnectivityLink,
    ConnectivityWordBlockSum,
    ConnectivityWordBlockPrefix,
    ConnectivityRanks,
    ConnectivityCounts,
    ConnectivityRetiredEdges,
    ConnectivityEdgeTables,
    VertexFanInit,
    VertexFanKeys,
    VertexFanTileScan,
    VertexFanTilePrefix,
    VertexFanHistogram,
    VertexFanPrefix,
    VertexFanScatter,
    VertexFanEmit,
    WeldTableInit,
    WeldInsert,
    WeldMarkReps,
    WeldBlockSum,
    WeldBlockPrefix,
    WeldScan,
    WeldEmit,
    WeldRemapCorners,
    WeldCompact,
    WeldWriteBack,
    VertexNormalDerive,
    RetessellateFaces,
    ElementWorkSeed,
    CornerClassificationCount,
    CornerClassificationPlan,
    CornerClassificationWrite,
    CornerClassificationBlocks,
    MeshClosureCount,
    MeshClosureExpand,
    MeshClosureEdgeVertices,
    MeshClosureTriangles,
    MarkSelectionNeighbors,
    UpdateSelectionBlocks,
    GatherSelectedElements,
    ConnectivityEditWork,
    SpatialFaceQueryCount,
    SpatialFaceQueryGather,
    SpatialFaceQueryExpand,
    TopologyIdentityInit,
    TopologyIdentityRetain,
    TopologyIdentityReplaced,
    TopologyIdentityNew,
    TopologyIdentityAssign,
    ElementWorkHistogram,
    ElementWorkPrefix,
    ElementWorkScatter,
    ElementWorkFinish,
    TopologyCollapseKeys,
    TopologyCollapseHistogram,
    TopologyCollapsePrefix,
    TopologyCollapseScatter,
    TopologyCollapseReduce,
    TopologyCollapseCarry,
    TopologyCollapseCenters,
    TopologySelection,
    TopologyZero,
    TopologyMarkHalfedges,
    TopologyMarkFaces,
    TopologyMarkRetainedEdges,
    TopologyLink,
    TopologyJump,
    TopologyConverge,
    TopologyDissolveRegions,
    TopologyDissolveWalk,
    TopologyDissolveRevert,
    TopologyJoinBest,
    TopologyJoinMatch,
    TopologyZeroVertices,
    TopologyMergeTable,
    TopologyMergeInsert,
    TopologyMergeQuery,
    TopologyLineKeys,
    TopologyFinalizeVertices,
    TopologyListFill,
    TopologyCountVertices,
    TopologyCountHalfedges,
    TopologyCountFaces,
    TopologyScanBlockSum,
    TopologyScanBlockPrefix,
    TopologyScanOffsets,
    TopologyScatterVertices,
    TopologyScatterHalfedges,
    TopologyScatterFaces,
    TopologyFaceTables,
    TopologyGatherVertices,
    InsetPreviewPositions,
    PositionVerticesGather,
    SpaceEvenlyGather,
    RelaxEdgeLoopsGather,
    CurveBetweenSelected,
    Circularize,
    FlattenGroups,
    PositionStatisticsGather,
    PositionStatisticsReduce,
    VertexSlideReference,
    RecalculateNormalFaceCenters,
    RecalculateNormalCenters,
    RecalculateNormalCandidates,
    RecalculateNormalOrientation,
    PlanarFacePlanes,
    WriteEditedPositions,
    EditFaceUvs,
    EditFaceColors,
    MeshletBoundsRefit,
    TopologyGatherCorners,
    TopologyCustomNormals,
    TopologyEdgeAttributes,
    LodNodeRefit,
    MeshletOwners,
    MeshletBuildElements,
    MeshletBuildMaterials,
    MeshletBuildInit,
    MeshletBuildBounds,
    MeshletBuildKeys,
    MeshletBuildHistogram,
    MeshletBuildHistogramPrefix,
    MeshletBuildScatter,
    MeshletBuildSegments,
    MeshletBuildTiles,
    MeshletBuildClusters,
    MeshletBuildOffsets,
    MeshletBuildEmit,
    MeshletBuildPrimitives,
    CloneCopyByteRuns,
    CloneGatherByRank,
    CloneRebaseByBlock,
    CloneRebaseByRank,
    Count,
};

struct MeshPipelines {
    explicit MeshPipelines(mtl::LibraryCache &);
    const mtl::ComputePipeline &operator[](MeshPass pass) const;
    void PrewarmAsync();

    mtl::LibraryCache &Libraries;
    mutable std::mutex Mutex;
    mutable std::array<std::optional<mtl::ComputePipeline>, size_t(MeshPass::Count)> Pipelines;
    std::jthread PrewarmWorker;
};

// Returns mesh pipelines.
// Each pass compiles when first requested.
MeshPipelines &GetMeshPipelines(state::Scene &);
