#!/bin/bash

ScriptDir="$(cd "$(dirname "${0}")" && pwd)"
ProjectRootDir="$(dirname "${ScriptDir}")"

find -E "${ProjectRootDir}/src" -regex '.*\.(cpp|hpp|c|cc|cxx|h|hh)' -exec clang-format -style=file -i {} \;
