#pragma once
#include <cstdint>
#include <string_view>
#include <type_traits>

namespace state {
using TypeId = uint32_t;
template<typename T> consteval std::string_view TypeName() {
    std::string_view text = __PRETTY_FUNCTION__;
    const auto begin = text.find("T = ") + 4;
    return text.substr(begin, text.rfind(']') - begin);
}
// Closed schema: adding a component or service assigns a compile-time slot here.
// Names keep concrete definitions in their domain TUs, including private service types.
inline constexpr std::string_view SchemaNames[] = {
    "fastfem::MassProperties",
    "std::variant<RotationQuat, RotationEuler, RotationAxisAngle>",
    "std::variant<primitive::Plane, primitive::Circle, primitive::Cuboid, primitive::IcoSphere, primitive::UVSphere, primitive::Torus, primitive::Cylinder, primitive::Cone>",
    "std::variant<Perspective, Orthographic>",
    "AcousticMaterial",
    "Active",
    "ActiveSamplerAnisotropy",
    "ActiveScene",
    "AdditiveBoxSelectBaseline",
    "AnimationTimelineView",
    "Armature",
    "ArmatureAnimation",
    "ArmatureModifier",
    "ArmatureObject",
    "ArmaturePose",
    "ArmaturePoseState",
    "AudioDeviceResource",
    "AudioOutputConfig",
    "AudioOutputMix",
    "AudioSamples",
    "AudioTrackers",
    "BodyPoseCache",
    "BoneActive",
    "BoneAdjacencyIndices",
    "BoneAttachment",
    "BoneConstraints",
    "BoneDisplayScale",
    "BoneIndex",
    "BoneInstanceStateDirty",
    "BoneJoint",
    "BoneJointEntities",
    "BoneSelection",
    "BoneSubPartOf",
    "BoxSelectState",
    "CameraName",
    "ColliderMaterial",
    "ColliderPolicy",
    "ColliderShape",
    "CollisionFilter",
    "CollisionSystem",
    "ContactDynamics",
    "ContactSurface",
    "EditMode",
    "EditSelectionDirty",
    "EnabledInteractionModes",
    "EntityDestroyTracker",
    "EntityNameCounts",
    "EnvironmentStore",
    "ExciteSelectionBaseline",
    "FrameState",
    "GizmoInteraction",
    "GltfObject",
    "GpuBuffers",
    "GpuSceneState",
    "Hidden",
    "Instance",
    "Interaction",
    "LastEvaluatedFrame",
    "LightIndex",
    "LightName",
    "LookingThrough",
    "MasterCapture",
    "MaterialDirty",
    "MaterialPreviewLighting",
    "MaterialStore",
    "MaterialVariants",
    "MaterializedTextures",
    "MeshActiveElement",
    "MeshBuffers",
    "MeshBvh",
    "MeshElementSelection",
    "MeshGeometryDirty",
    "MeshHandle",
    "MeshMaterialAssignment",
    "MeshMaterialSlotSelection",
    "MeshName",
    "MeshPipelines",
    "MeshPositionsChanged",
    "MeshShadingDirty",
    "MeshShadingSummary",
    "MeshSourceLayout",
    "MeshStore",
    "ModalAudio",
    "ModalEigenSummary",
    "ModalGain",
    "ModalModes",
    "ModalSolveJobs",
    "ModalSolveSettings",
    "ModalSoundControls",
    "ModalTuning",
    "ModalWarmStart",
    "ModelsBuffer",
    "MonitorLimiter",
    "MorphWeightAnimation",
    "MorphWeightGpuRange",
    "MorphWeightState",
    "Name",
    "NodeTransformAnimation",
    "ObjectExtrasTag",
    "ObjectKind",
    "OrbitToActive",
    "ParentInverse",
    "Path",
    "PbrMeshFeatures",
    "PendingBoxSelect",
    "PendingEditElementClick",
    "PendingEnvironmentImport",
    "PendingHide",
    "PendingImportMesh",
    "PendingLightRemovals",
    "PendingPick",
    "PendingRenderRequest",
    "PendingSceneWorldClear",
    "PendingSetEditMode",
    "PendingShaderRecompile",
    "PendingTextureUploads",
    "PendingTransform",
    "PhysicsBodyHandle",
    "PhysicsCacheInvalid",
    "PhysicsConstraintHandle",
    "PhysicsContactImpacts",
    "PhysicsJoint",
    "PhysicsJointDef",
    "PhysicsMaterial",
    "PhysicsMotion",
    "PhysicsSimulationSettings",
    "PhysicsState",
    "PhysicsSustainedContacts",
    "PhysicsVelocity",
    "Pipelines",
    "PlaybackFrame",
    "PosedLocal",
    "PunctualLight",
    "RealImpactActiveMicrophone",
    "RealImpactMicrophone",
    "RealImpactVertices",
    "Recording",
    "RenderInstance",
    "RenderedLighting",
    "ReportContacts",
    "RotationUiDriving",
    "SamplePlayback",
    "ScaleLocked",
    "Scene",
    "SceneClearHandlers",
    "SceneMembership",
    "SceneNode",
    "SceneSetupHandlers",
    "Selected",
    "SelectionSlots",
    "SelectionXRay",
    "ShadeSmoothAngle",
    "SoundVertices",
    "SoundVerticesModel",
    "SourceCameraIndex",
    "SourceCollisionFilterIndex",
    "SourceEmptyName",
    "SourceLightIndex",
    "SourceMatrixTransform",
    "SourceMeshIndex",
    "SourceMeshKind",
    "SourceNodeIndex",
    "SourceObjectName",
    "SourceParentNodeIndex",
    "SourcePhysicsJointDefIndex",
    "SourcePhysicsMaterialIndex",
    "SourceSceneIndex",
    "SourceSiblingIndex",
    "StartBoneLength",
    "StartScreenTransform",
    "StartTransform",
    "Striker",
    "StudioEnvironment",
    "SubElementOf",
    "SurfaceFinishKey",
    "SurfaceRelief",
    "SurfaceSoundControls",
    "TetBuffers",
    "TextureStore",
    "TimelinePlayback",
    "TimelineRange",
    "Transform",
    "TransformGizmoState",
    "TriggerNodes",
    "TriggerTag",
    "VertexForce",
    "VertexSamples",
    "VertexStoreId",
    "VideoRecording",
    "ViewCamera",
    "ViewportConsumerFence",
    "ViewportDisplay",
    "ViewportExtent",
    "ViewportIcons",
    "ViewportRenderResources",
    "ViewportTheme",
    "WindowsState",
    "WorkspaceLights",
    "WorldTransform",
    "action::DragFieldStart",
    "action::Errors",
    "audio_changes::AudioConfig",
    "audio_changes::AudioMix",
    "audio_changes::ContactDynamicsDerivation",
    "audio_changes::ContactReportingDerivation",
    "audio_changes::ModalGain",
    "audio_changes::ModalSoundControls",
    "audio_changes::ModalTuning",
    "audio_changes::ModelRescaleEdit",
    "audio_changes::RecordingStart",
    "audio_changes::SoundVerticesDerivation",
    "audio_changes::VertexForce",
    "changes::ActiveAnimationClip",
    "changes::ActiveInstance",
    "changes::ActiveMaterialVariant",
    "changes::BoneSelection",
    "changes::CameraLens",
    "changes::ColliderPolicy",
    "changes::CollisionFilterDef",
    "changes::CollisionSystemDef",
    "changes::InteractionMode",
    "changes::MaterializedTextures",
    "changes::Materials",
    "changes::MeshActiveElement",
    "changes::MeshGeometry",
    "changes::MeshMaterial",
    "changes::MeshShading",
    "changes::NewBufferEntity",
    "changes::ObjectCreated",
    "changes::PbrSpecialization",
    "changes::PhysicsBodyMesh",
    "changes::PhysicsGeometry",
    "changes::PhysicsHierarchy",
    "changes::PhysicsJoint",
    "changes::PhysicsJointDef",
    "changes::PhysicsMaterial",
    "changes::PhysicsMaterialDef",
    "changes::PhysicsMotion",
    "changes::PhysicsPose",
    "changes::PhysicsShape",
    "changes::PhysicsTrigger",
    "changes::PunctualLight",
    "changes::RenderInstanceCreated",
    "changes::Rerecord",
    "changes::Rotation",
    "changes::SceneView",
    "changes::SceneWorld",
    "changes::Selected",
    "changes::SoundVertices",
    "changes::SoundVerticesUpdated",
    "changes::StudioEnvironment",
    "changes::TetMesh",
    "changes::TimelineRange",
    "changes::TransformDirty",
    "changes::TransformEnd",
    "changes::TransformPending",
    "changes::VertexForce",
    "changes::ViewportDisplay",
    "changes::ViewportTheme",
    "changes::WorkspaceLights",
    "changes::WorldTransform",
    "gltf::SourceAssets",
    "mtl::BindlessSet",
    "mtl::Context",
    "mtl::LibraryCache",
    "project::Assets",
    "project::Project *",
    "state::DirtySet",
    "state::Entity",
    "std::unique_ptr<ValidationSession>",
    "std::vector<ComponentEventHandler>",
    "surface_changes::SoundControls",
    "surface_changes::SurfaceEdit",
    "surface_changes::SurfaceGeometry",
    "surface_changes::SurfaceMaterial",
};
inline constexpr size_t SchemaSize = sizeof(SchemaNames) / sizeof(*SchemaNames);
constexpr bool SameName(std::string_view a, std::string_view b) {
    constexpr std::string_view anonymous = "(anonymous namespace)::";
    size_t i = 0, j = 0;
    while (i < a.size() || j < b.size()) {
        if (a.substr(i).starts_with(anonymous)) {
            i += anonymous.size();
            continue;
        }
        if (b.substr(j).starts_with(anonymous)) {
            j += anonymous.size();
            continue;
        }
        if (i < a.size() && a[i] == ' ') {
            ++i;
            continue;
        }
        if (j < b.size() && b[j] == ' ') {
            ++j;
            continue;
        }
        if (i == a.size() || j == b.size() || a[i++] != b[j++]) return false;
    }
    return true;
}
template<typename T> inline constexpr TypeId TypeIndex = [] {
    constexpr auto name = TypeName<T>();
    for (TypeId i = 0; i < SchemaSize; ++i)
        if (SameName(name, SchemaNames[i])) return i;
    return TypeId(SchemaSize);
}();
template<typename T> consteval TypeId Type() {
    constexpr auto index = TypeIndex<std::remove_cv_t<T>>;
    static_assert(index < SchemaSize, "Type is missing from the MeshEditor state schema");
    return index;
}
} // namespace state
